library:
  source-dirs: src
dependencies:
- base-noprelude >= 4.7
- MyPrelude
- containers
- transformers
- mtl
- arithmoi
- integer-roots
- semirings
- monad-loops
- lattices
- monoid-subclasses
- groups
- semigroupoids
- comonad
- algebraic-graphs
- IntervalMap
- mono-traversable
- profunctors
- witherable-class
- these
- tree-traversals
# - data-ordlist
tests:
  full:
    main:                Main.hs
    source-dirs:         test
    dependencies:
    - dio
    - microspec
default-extensions:
- AllowAmbiguousTypes
- ApplicativeDo
- Arrows
- BangPatterns
- BinaryLiterals
- BlockArguments
- ConstrainedClassMethods
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- DisambiguateRecordFields
- DoAndIfThenElse
- DuplicateRecordFields
- EmptyCase
- EmptyDataDecls
- EmptyDataDeriving
- ExistentialQuantification
- ExplicitForAll
- ExplicitNamespaces
- ExtendedDefaultRules
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTSyntax
- GADTs
- GeneralizedNewtypeDeriving
- HexFloatLiterals
- ImplicitParams
- ImportQualifiedPost
- InstanceSigs
- KindSignatures
- LambdaCase
- LiberalTypeSynonyms
- MagicHash
- MonadComprehensions
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NamedWildCards
- NoMonomorphismRestriction
- NoStarIsType
- NondecreasingIndentation
- NumDecimals
- NumericUnderscores
- OverloadedLabels
- OverloadedStrings
- PackageImports
- ParallelArrays
- ParallelListComp
- PartialTypeSignatures
- PatternGuards
- PatternSynonyms
- PolyKinds
- PostfixOperators
- QuantifiedConstraints
- QuasiQuotes
- RankNTypes
- RecordWildCards
- RecursiveDo
- RelaxedLayout
- RelaxedPolyRec
- RoleAnnotations
- ScopedTypeVariables
- StandaloneDeriving
- StandaloneKindSignatures
- TransformListComp
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeInType
- TypeOperators
- TypeSynonymInstances
- UnboxedSums
- UnboxedTuples
- UnicodeSyntax
- ViewPatterns
name: dio
verbatim:
  cabal-version: 2.4
